#!/bin/bash
set -e

# Update icon cache
if which update-icon-caches >/dev/null 2>&1; then
    update-icon-caches /usr/share/icons/hicolor
fi

# Update desktop database
if which update-desktop-database >/dev/null 2>&1; then
    update-desktop-database /usr/share/applications
fi

# Set permissions
chmod +x /opt/sn/thunder_wings/bin/thunder_wings

exit 0
